import { UserRole as PrismaUserRole } from '../../../generated/prisma/enums'
import { describe, expect, it } from 'vitest'
import { DEFAULT_USER_ROLE, isUserRole, USER_ROLES } from './userRole'

const roleCases = [
  { name: 'accepts the administrator role', input: 'ADMIN', expected: true },
  { name: 'accepts the viewer role', input: 'VIEWER', expected: true },
  { name: 'rejects guest as a registered-user role', input: 'GUEST', expected: false },
  { name: 'rejects an unrelated string', input: 'EDITOR', expected: false },
  { name: 'rejects a non-string value', input: null, expected: false },
]

describe('UserRole', () => {
  it.each(roleCases)('$name', ({ input, expected }) => {
    expect(isUserRole(input)).toBe(expected)
  })

  const contractCases = [
    {
      name: 'supports exactly the roles generated by Prisma',
      input: [...USER_ROLES],
      expected: Object.values(PrismaUserRole),
    },
    {
      name: 'defaults registered users to viewer',
      input: DEFAULT_USER_ROLE,
      expected: PrismaUserRole.VIEWER,
    },
  ]

  it.each(contractCases)('$name', ({ input, expected }) => {
    expect(input).toEqual(expected)
  })
})
